Week 1
========================================================

downloading data
```{r}
#set working directory
setwd("~/Coursera - R/Getting and Cleaning Data")
if(!file.exists('data')){
  dir.create('data')
}
#download csv from url
fileURL<-'https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv?accessType=DOWNLOAD'
download.file(fileURL, destfile='./data/commSurvey.csv')
list.files('./data')
dateDownloaded<-date()
dateDownloaded

#read data into R
commSurvey<-read.csv('./data/commSurvey.csv', header=TRUE)

#list variables
ls(commSurvey)
#property value = 'VAL'
#see codebook (https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FPUMSDataDict06.pdf) for variable definitions

# Count number of properties valued at >$1M
commSurveyRich <- commSurvey[ which(commSurvey$VAL=='24'),]
length(commSurveyRich$VAL)


```

You can also embed plots, for example:

```{r}
#Read rows 18-23 and columns 7-15 into R from .xlsx file and assign the result to a variable called dat 
library(xlsx)
colIndex <- 7:15
rowIndex <- 18:23
dat<-read.xlsx('./data/NGAP_data.xlsx', sheetIndex=1, 
               colIndex=colIndex, rowIndex=rowIndex)

sum(dat$Zip*dat$Ext,na.rm=T) #provided on quiz

```

```{r}
#Read in xml and subset
library(XML)
library(RCurl) #suggestion from R forum to address error ' XML content does not seem to be XML'
fileUrl<- 'https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Frestaurants.xml'
#doc<-xmlTreeParse(fileUrl, useInternal=TRUE)  #not supported by RCurl
doc<-getURL(fileUrl, ssl.verifypeer = FALSE)
doc<-xmlParse(doc)
rootNode<-xmlRoot(doc)
xmlName(rootNode)

xmlSApply(rootNode, xmlValue)
xpathSApply(rootNode, '//zipcode', xmlValue)
zip<- rootNode[ which(doc$zipcode=='21231'),]
length(zipcode)
```

```{r}
#download csv from url
fileURL<-'https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06pid.csv?accessType=DOWNLOAD'
download.file(fileURL, destfile='./data/commSurvey2.csv')
list.files('./data')
dateDownloaded<-date()
dateDownloaded

#read data into R as data.table
library(data.table)
DT<-fread('./data/commSurvey2.csv', header=TRUE)

#DT<-read.csv('./data/commSurvey2.csv', header=TRUE)
#DT<- as.data.table(DT)

tables()

#Subsetting rows in data.table
# DT[2,] # only row 2
# DT[DT$y=='a'] #only rows with value = 'a' for variable 'y'

# add new columns to data.table
#DT<- DT[,w:=z^2]  # ':' indcates new column named 'w' '=z^2' defines calculation for variable 'w'

#Multiple operations
#DT[, m:={tmp<-(x+z); log2(tmp+5)}]  # the last expression is returned as specified variable

#special Variables
# DT[, .N, by=x] # count of the number of occurances, grouped by variable 'x'



# the fastest way to calculate the average value of the variable, pwgtp15, broken down by sex using the data.table package? 
DT[,mean(pwgtp15),by=SEX]

```

